// controllers/shipmentController.js
const Order = require('../models/Order');

// Function to generate a random tracking number
const generateTrackingNumber = () => {
  return 'TRK-' + Math.random().toString(36).substring(2, 10).toUpperCase();
};

// Fetch all shipped orders
const getShippedOrders = async (req, res) => {
  try {
    const shippedOrders = await Order.find({ status: 'shipped' });
    res.json(shippedOrders);
  } catch (error) {
    res.status(500).json({ message: 'Failed to fetch shipped orders', error });
  }
};

// Update shipment details for a specific order


// Update shipment details for a specific order
const updateShipmentDetails = async (req, res) => {
  const { shipmentDate } = req.body;
  const { id } = req.params;  // 'id' is the Order ID passed via URL parameters

  // Auto-generate tracking number
  const autoGeneratedTrackingNumber = generateTrackingNumber();

  try {
    // Find order by Order ID and update the shipment details
    const updatedOrder = await Order.findByIdAndUpdate(
      id,  // Order ID to find the specific order
      { 
        trackingNumber: autoGeneratedTrackingNumber,
        shipmentDate: shipmentDate || new Date(),  // Use provided date or default to current date
        status: 'shipped',  // Mark order as shipped
      },
      { new: true }  // Return the updated order
    );

    if (!updatedOrder) {
      return res.status(404).json({ message: 'Order not found' });
    }

    res.json(updatedOrder);
  } catch (error) {
    res.status(500).json({ message: 'Failed to update shipment details', error });
  }
};

module.exports = {
  getShippedOrders,
  updateShipmentDetails,
};
